source "https://rubygems.org"

gem 'guard'
gem 'guard-compass'
gem 'guard-shell'
gem 'guard-livereload'
gem 'asciidoctor'
gem 'tilt'
gem 'slim'
gem 'guard-asciidoc', :github => 'asciidoctor/guard-asciidoc'
