source "https://rubygems.org"

group :development do
  gem 'guard'
  gem 'guard-compass'
  gem 'guard-shell'
  gem 'guard-livereload'
  gem 'tilt'
  gem 'slim'
  gem 'guard-asciidoc', :github => 'asciidoctor/guard-asciidoc'
end
